create database if not exists db;
use db;

create table if not exists libri(
id int auto_increment primary key,
titolo varchar(255),
autore varchar(255),
codice_ISBN varchar(255),
data_aggiunta varchar(255),
data_eliminazione varchar(255),
trama text,
numero_letture int unsigned,
rating int unsigned,
pagine json,
evidenza bool,
data_pubblicazione varchar(255),
numero_pagine int,
mark bool
);

create table if not exists utenti(
id int auto_increment primary key,
nome varchar(255),
cognome varchar(255),
email varchar(255)
);

create table if not exists utenti_libri(
id int auto_increment primary key,
lista_libri json,
lista_libri_eliminati json
);

drop table libri;
drop table utenti_libri;
truncate libri;
truncate utenti_libri;
desc libri;
desc utenti_libri;
select * from libri;
select * from utenti;
select * from utenti_libri;

insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Tutti su questo treno sono sospetti", "Benjamin Stevenson", "2000000130361", null, null, "Ernest Cunningham è nei guai. Dopo essere diventato famoso per aver scritto un true crime sulla sua famiglia – una famiglia micidiale: hanno tutti ucciso qualcuno –, il suo agente letterario e il suo editore gli chiedono con insistenza un nuovo libro. Ma dove trovare l’ispirazione, senza che qualcuno ci rimetta la pelle? L’occasione si presenta sotto forma di un invito al Festival Australiano del Giallo. In omaggio ad Assassinio sull’Orient Express di Agatha Christie, gli organizzatori hanno deciso di riunire un gruppo di celebri giallisti a bordo del Ghan, il treno che attraversa l’Australia, da Darwin a Adelaide. Durante il viaggio, Ernie avrà modo di confrontarsi con i colleghi e forse, chissà, di mettersi finalmente al lavoro. Neanche il tempo di partire che ci scappa il morto. Per deformazione professionale, ciascuno dei giallisti inizia subito a elaborare teorie in base alla propria specializzazione: c’è chi procede per deduzione, chi veste i panni del medico legale e chi traccia il profilo psicologico del possibile assassino. A bordo sono tutti sospetti. Sulla carta sanno tutti come ragiona un detective e, prima ancora, come si commette un crimine, ma chi è passato dalla teoria alla pratica?", 0, 4, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-12-6", 368, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Amore senza fine. Love me love me. Vol. 3", "Stefania S.", "9788855441865", null, null, "L'amore non è mai sbagliato. È ormai giunto l'ultimo anno di liceo per June. Le cose tra lei e James non potrebbero andare meglio di così, ora che entrambi hanno ammesso i sentimenti che provano l'uno per l'altra. Le cose cambiano quando lui, dopo una visita misteriosa a casa, scompare senza lasciare traccia. Chiedere aiuto alla polizia non è un'opzione e così la ragazza non può fare altro che rivolgersi a William. Ben presto si renderà conto che sono ancora troppi i segreti che si nascondono dietro la famiglie che credeva di conoscere e che coinvolgono le persone a cui tiene di più. Ma può l'amore sopravvivere a tutto? Può un legame essere così forte da durare per sempre?", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2021-3-25", 672, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("La meraviglia del tutto. Conversazioni con Massimo Polidoro", "Piero Angela, Massimo Polidoro", "9788804784982", null, null, "Questo è probabilmente l'ultimo libro che scrivo. Non pensavo di farlo, ma poi ho riflettuto che forse ne valeva la pena. Adesso vorrei dire anch'io quello che penso, le domande che mi pongo, le cose che ho compreso… È un libro che forse voglio scrivere anche per me stesso, oltre che per i lettori.' Da tempo Piero Angela lavorava a queste pagine, frutto di un confronto – durato decenni – con il suo storico collaboratore Massimo Polidoro. Una conversazione, è il caso di dirlo, sui massimi sistemi: l'universo, la natura, l'uomo. Si parla di scienza insomma, che lo appassionava e che era tanto bravo a divulgare. 'Pensa come uno scienziato', oltre a essere sempre stato il suo consiglio ai giovani, è anche la chiave di lettura e di comprensione del presente che viene loro offerta da questo libro. Ogni cosa della vita, ogni argomento può, anzi deve essere affrontato con la razionalità tipica del metodo scientifico. Ma allo stesso tempo non bisogna mai perdere la curiosità, l'umiltà e il senso di meraviglia. Solo così si capisce, e si cresce. La meraviglia del tutto è una lezione di vita che accompagna il lettore in un viaggio alle origini dell'uomo, questo 'pezzetto di universo che ha acquisito la capacità di voltarsi indietro e di ricostruire la propria storia straordinaria'. Ogni capitolo apre una porta che dà su porte successive, e la grande capacità narrativa di Angela cattura la curiosità del lettore e lo trascina nell'affascinante avventura della conoscenza. Questo libro non sarebbe stato possibile senza Massimo Polidoro, l'allievo che nel corso di trent'anni ha 'interrogato' il maestro stimolandolo con le sue domande. Che sono poi le stesse che tutti noi ci facciamo. E a cui Piero Angela risponde con la chiarezza e l'onestà intellettuale che abbiamo sempre ammirato.", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-7-5", 540, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("La mia Ingeborg", "Tore Renberg", "9791259671257", null, null, "Tollak è un uomo pieno di contraddizioni: testardo e sensibile, rude e orgoglioso. Un uomo impossibile, a detta di molti. Ormai vecchio e solo, barricato nella sua fattoria, non fa che imprecare contro il mondo che da tempo, per lui, ha smesso di avere senso. L’unica persona che lo teneva attaccato alla vita era lei: sua moglie Ingeborg, amatissima, scomparsa da qualche anno. “Tollak di Ingeborg”, lo chiamava la gente del paese. I suoi due figli, ora adulti, hanno abbandonato la valle, teatro di un’infanzia difficile; oggi vivono in città e passano a trovarlo di rado. Soltanto Oddo è rimasto con lui: “Oddoloscemo”, per i vicini, lo zimbello di tutti, un ragazzo problematico di cui si prende cura da quando, ancora bambino, è stato abbandonato dalla madre. La vita di Tollak, soprattutto negli ultimi anni, è stata avvolta nel silenzio: troppo difficile dare voce alla rabbia che gli brucia dentro. Ma ora è giunto il momento di parlare, di raccontare finalmente la sua verità. Così, l’uomo insiste affinché sua figlia e suo figlio tornino a casa ancora una volta, forse l’ultima. Prima che sia troppo tardi ha bisogno di condividere il suo segreto. O meglio, i suoi segreti: le verità che Tollak ha sempre tenuto per sé sono molte, e sono una più sconvolgente dell’altra.", 0, 4, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-2-6", 180, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Atalanta", "Jennifer Saint", "4788845412820", null, null, "Quando il sovrano di Arcadia vede nascere una figlia femmina, anziché l’erede maschio che tanto desiderava, la sua decisione è immediata: la bambina sarà abbandonata a morire sulle pendici di una montagna. Ma il destino ha in serbo ben altro per la piccola Atalanta, che prima viene salvata e allevata da un’orsa e poi, una volta cresciuta, viene scelta dalla dea Artemide per vivere nella foresta insieme alle sue ninfe. La giovane diventa così un’abilissima cacciatrice, forte e veloce quasi quanto Artemide stessa. Scoprendo che un equipaggio di eroi, gli Argonauti, sta per imbarcarsi in una missione impossibile alla ricerca del vello d’oro, la dea decide di inviare Atalanta in suo nome, con un unico avvertimento: se si sposerà, condannerà la sua esistenza alla rovina. Ma la ragazza non teme alcuna sfida, ed è pronta a lottare contro il disprezzo dei suoi compagni di viaggio e del loro capo, Giasone, per dimostrare che anche le donne meritano di diventare leggenda.", 0, 3, '["page_1", "page_2", "page_3", "page_4"]', false, "2022-5-16", 352, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Cose spiegate bene. L'importante è partecipare", "Il Post, Nicola Sofri", "6788870918151", null, null, "Tra entusiasmi, problemi, successi, fallimenti, settimane emozionanti e retoriche sfinenti, le Olimpiadi hanno occupato quasi 130 anni di storia del mondo: con una serie di eventi ineludibili, protagonisti dello sport, ma anche della politica internazionale, dei cambiamenti sociali, della comunicazione e dei media, della scienza, e dei rapporti tra gli stati e i popoli. Questo numero di COSE Spiegate bene ne racconta storie note e meno note, ne spiega dinamiche, cambiamenti ed economie, raccoglie il bene delle Olimpiadi e ne riporta le critiche: dando a tutti da prepararsi in attesa delle gare e da intrattenersi e informarsi in attesa degli inni e delle premiazioni. Da come si scelgono i paesi ospitanti, a chi paga tutto quanto, a quali atleti sono diventati leggende vincendo, a quali ci sono riusciti perdendo, a cosa succede a chi partecipa senza gran fama, fino ai momenti che sono diventati Storia non sportiva, a volte drammatica. L’importante è conoscere le cose, per noialtri che non partecipiamo. Con testi di Lia Capizzi, Paolo Condò, Luigi Datome, Beatrice Vio Grandis e della redazione del Post. A cura del Post e di Nicola Sofri. Illustrazioni di Giordano Poloni.", 0, 2, '["page_1", "page_2", "page_3", "page_4"]', false, "2020-8-4", 312, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Iron Flame", "Rebecca Yarros", "8788820077341", null, null, "Tutti si aspettavano che Violet Sorrengail morisse durante il suo primo anno all’accademia militare di Basgiath, compresa lei stessa. Ma la Trebbiatura è stata solo la prima, difficilissima prova per eliminare i candidati più insicuri, indegni e sfortunati. Ora inizia l’addestramento vero e proprio, e Violet già si chiede come farà a superarlo. Perché non sarà soltanto terribilmente estenuante, brutale e progettato per testare la capacità dei cavalieri di resistere al dolore oltre ogni limite. Il vero pericolo è il nuovo vicecomandante, che ha deciso di dimostrare a ogni costo quanto la ragazza sia inadatta al posto che si è guadagnata a fatica, a meno che non tradisca l’uomo che ama. Forse il corpo di Violet è più debole di quello degli altri, ma di certo non le mancano né l’ingegno, né una volontà di ferro. E soprattutto, il vicecomandante non tiene conto della lezione più importante di Basgiath: i cavalieri di draghi si fanno le regole da soli. Ma la determinazione a sopravvivere non sarà sufficiente quest’anno. Perché Violet conosce il vero segreto nascosto da secoli all’accademia militare di Basgiath e niente, nemmeno il fuoco dei draghi, potrebbe essere sufficiente a salvarli.", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-4-12", 672, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Sepolcro in agguato. Un'indagine di Cormoran Strike", "Robert Galbraith", "9768831017992", null, null, "L’ormai famosa agenzia Strike ed Ellacott ha risolto molti casi inestricabili. Quello che rimane non risolto è il rapporto trai due soci, segnato da un’amicizia profonda e inquieta, tra slanci imprevedibili e sotterranee gelosie. Quando l’anziano Sir Colin Edensor chiede il loro aiuto per tirar fuori il figlio Will da una setta che lo ha plagiato, i due accettano senza esitare. In nome della lotta per un mondo migliore, la Universal Humanitarian Church allontana i suoi membri dai loro affetti e li induce a elargire enormi donazioni, diventando sempre più potente. Peccato che dietro a un leader dal carisma innegabile ci sia un passato sordido e ben più di una morte sospetta. Entrare sotto copertura nella sede principale, una fattoria sperduta nel cuore del Norfolk, sembra l’unica soluzione, e Robin è pronta a farlo. Ma intelligenza e preparazione potrebbero non bastarle: addentrarsi nel lato oscuro dell’UHC si rivelerà molto rischioso, tra vendette soprannaturali, ricatti ed ex adepti terrorizzati. Uniti come non mai, Robin e Strike dovranno mettere in campo non solo le loro capacità professionali, ma anche le risorse più personali e i ricordi più intimi, in una delle sfide più difficili e coinvolgenti in assoluto.", 0, 1, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-8-3", 1120, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Morte nel chiostro", "Marcello Simoni", "3788834616390", null, null, "Città di Ferrara, ottobre 1187. Mentre il popolo si assiepa intorno alla grande cattedrale per assistere alle esequie di papa Urbano III, tre uomini avvolti in mantelli da pellegrini discutono sulla necessità di ritrovare una preziosa reliquia sparita dai forzieri del pontefice subito dopo il suo decesso. Il giorno dopo, in una selva al confine dei sobborghi cittadini, una monaca viene trovata impiccata nel chiostro del monastero femminile di San Lazzaro. Benché sembri trattarsi di un suicidio, due consorelle della defunta sospettano che quella tragica morte sia collegata a un intrigo ordito al di fuori del convento. La prima è Engilbera di Villers, la sapiente badessa dedita a completare un trattato sulle piante velenose lasciatole in eredità dalla sua venerabile maestra, Ildegarda di Bingen. La seconda è Beatrice de’ Marcheselli, una giovane vedova entrata come novizia a San Lazzaro per sfuggire alle attenzioni del cognato, che la vorrebbe prendere in sposa per appropriarsi della sua dote. Scavando nei segreti della loro defunta consorella, le due monache scopriranno un inaspettato legame con la morte di papa Urbano e con la sparizione di una misteriosa reliquia proveniente da San Giovanni d’Acri. Una reliquia che sembra aver lasciato dietro di sé una scia di delitti.", 0, 4, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-1-24", 352, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("L'amore necessario. La forza che muove il mondo", "Marcello Veneziani", "1788829720156", null, null, "Viviamo in un’epoca dominata da un individualismo assoluto, dove i legami si possono revocare se viene messo a rischio questo imperativo categorico. Energia particolare e universale che anima la vita, l’amore è invece tensione a completarsi, «eccedenza e carenza di sé che spingono verso l’altro per colmarsi e riversarsi». Dopo 'La Cappa', in cui invita a prendere atto della scomparsa di tradizioni, natura, bellezza, simboli e differenze, e 'Scontenti', in cui affronta un presente che non soddisfa più, Marcello Veneziani scorge una via d’uscita dalla solitudine che ci attanaglia, lasciandoci orfani di una visione generale della realtà. In una società frammentata, dove l’individuo è sempre più chiuso nel proprio recinto, la condivisione introduce un elemento di speranza. In un tempo governato da un patologico narcisismo di massa, l’amore per la vita, l’altro, la famiglia, la patria, il mondo, il destino e la verità sembrano essere le uniche vie per salvarci dall’io e dalla minaccia del niente.", 0, 3, '["page_1", "page_2", "page_3", "page_4"]', false, "2021-11-25", 224, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("The extraordinaires", "T.J. Klune", "9788804767022", null, null, "Nick Bell non ha niente di straordinario. Ma essere il più popolare autore di fanfiction nella comunità di appassionati degli Straordinari è già qualcosa. Mentre eroi mascherati dotati di superpoteri danno prova di grande coraggio tra i cieli e nei bassifondi della città, Nick si accontenta di inventare storie sulle loro imprese eroiche e romantiche, che poi pubblica devotamente sul web invece di finire i compiti. Questo, almeno, fino a quando non incontra il più forte tra i suoi idoli, Shadow Star: scrivere di supereroi non gli basta più, ora vuole essere uno di loro. Decide quindi di diventare anche lui qualcosa di più. Qualcosa di straordinario.", 0, 2, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-6-15", 408, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Tutto su di noi", "Romana Petri", "2788804787655", null, null, "Marzia, 'dall'andatura marziale', si racconta con furia, violenza, spudoratezza. La sua è una prima persona che morde e che si muove dentro lo spazio asfissiante di una famiglia malata, tremenda, cattiva. Cresce nella periferia di Roma, con un padre crudele e codardo e una madre devota, sino allo strazio, al coniuge infedele. Mentre il fratello, cuffie sulle orecchie, si estrania sino all'indifferenza, Marzia combatte, e nulla le viene risparmiato. Educa il suo fisico asciutto alla lotta greco‐romana e impara a mettere fra sé e il mondo la barriera del suo corpo. Ma non basta. Non può sfuggire al conflitto, alla strategia del ragno che padre e madre, in maniera diversa, le tessono intorno. Ha creduto e continua a credere che esiste la perfezione: l'ha vista in un cane che non è riuscita a difendere e l'ha vista in un ragazzo incontrato su un sentiero di montagna. L'ha vista ma la sa perduta, minacciata dalla volgarità di una pernacchia. Per arrivare a una via d'uscita sono necessari un sacrificio, una svolta, una chiusura di conti. Sul sentiero sgretolato degli affetti, Marzia avanza impavida al di là della scuola di rabbia, rimpianto e morbosa dedizione in cui si è formata. Avanza come un cowboy o ancora meglio come la donna libera che ha sempre voluto essere.", 0, 1, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-1-11", 216, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("La prigione", "Georges Simenon", "4788845938535", null, null, "Ad Alain Poitaud, direttore appena trentaduenne di un settimanale di enorme successo, bastano poche ore per smettere di essere l’uomo che è stato e «diventare un altro». Accade in una piovosa sera di ottobre, allorché, tornando a casa per cambiarsi in vista di una cena in compagnia della moglie Jacqueline e della piccola corte di cui è solito circondarsi, trova ad aspettarlo davanti al portone un ispettore della Polizia giudiziaria. Poco dopo, al Quai des Orfèvres, si sentirà dire che Jacqueline ha ucciso la sorella minore, Adrienne, con un colpo di pistola, chiudendosi poi in un mutismo assoluto. La stampa ci metterà poco a scoprire che con Adrienne, per parecchi anni, Alain è andato a letto regolarmente, e parlerà di «dramma della gelosia», ma lui – l’uomo cinico, superficiale, mondano, il donnaiolo incallito sempre pronto a fare dell’ironia – comincerà a chiedersi quale sia stato il vero motivo di quel gesto. E mentre la polizia conduce la sua indagine, si interrogherà su quella giovane donna accondiscendente e discreta (tanto che fin dall’inizio l’ha chiamata Micetta), che ha sposato quasi per gioco, che gli è sempre stata accanto senza chiedere niente – ma, soprattutto, in un crescendo di smarrimento e di angoscia, si interrogherà su se stesso.", 0, 3, '["page_1", "page_2", "page_3", "page_4"]', false, "2019-12-1", 170, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Un animale selvaggio", "Joël Dicker", "7788834617021", null, null, "2 luglio 2022, due ladri stanno per rapinare una importante gioielleria di Ginevra. Ma questo non sarà un colpo come tutti gli altri. Venti giorni prima, in un elegante sobborgo sulle rive del lago, Sophie Braun sta per festeggiare il suo quarantesimo compleanno. La vita le sorride, abita con il marito Arpad e i due figli in una magnifica villa al limitare del bosco. Sono entrambi ricchi, belli, felici. Ma il loro mondo idilliaco all’improvviso s’incrina. I segreti che Arpad custodisce cominciano a essere troppi perché possano restare nascosti per sempre. Il loro vicino, un poliziotto sposato dalla reputazione impeccabile, è ossessionato da quella coppia perfetta e da quella donna conturbante. La osserva, la ammira, la spia in ogni momento dell’intimità. Nel giorno del compleanno di Sophie, un uomo misterioso si presenta con un regalo che sconvolgerà la sua vita dorata. I fili che intrappolano queste vite portano lontano nel tempo, lontano da Ginevra e dalla villa elegante dei Braun, in un passato che insegue il presente e che Sophie e Arpad dovranno affrontare per risolvere un intrigo diabolico, dal quale nessuno uscirà indenne. Nemmeno il lettore.", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2022-3-7", 416, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Fili d'ombra", "Christian Guay-Poliquin", "9788829715534", null, null, "In una magnifica foresta canadese, tra felci lussureggianti e cespugli minacciosi, un uomo solo cammina verso il capanno dove la sua famiglia si è rifugiata dopo un blackout generalizzato. Dimenticati i rigori dell’inverno, in una terra diventata di nessuno, la natura si sta riprendendo lo spazio che le compete e muoversi diventa via via più difficile, anche perché sui sentieri battuti imperversano bande di disperati pronti a tutto. In preda alla paura, alla fame e alla sete, l’uomo sta per arrendersi a questa selva oscura quando incontra un ragazzino. Dimostra dodici anni, sembra non avere paura di niente, e si unisce a lui come se lo conoscesse da sempre. Insieme proseguiranno il cammino e, nell’abbraccio di un paesaggio sontuoso e malevolo, sperimenteranno modi inediti per sopravvivere, sperare, e perfino per amare. Nella prosa esatta, minuziosa, ferocemente asciutta di Guay-Poliquin, prende vita un romanzo palpitante e attualissimo, che rivisita i classici della sopravvivenza nella natura e, attraverso una storia avventurosa e commovente, si interroga sul significato più profondo – e non convenzionale – dell’essere famiglia.", 0, 4, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-9-17", 288, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Mantieni il bacio. Lezioni brevi sull'amore", "Massimo Recalcati", "5788807895258", null, null, "L'amore dura solo il tempo di un bacio? La sua promessa è destinata fatalmente a dissolversi? La fiamma che brucia può durare eternamente? Oppure ogni amore finisce inevitabilmente? Il desiderio per esistere non ha forse sempre bisogno del Nuovo? Il matrimonio è allora condannato a essere solo il cimitero del desiderio? E il lessico famigliare a esaurire il lessico amoroso? Può esistere un amore che dura nel tempo mentre continua a bruciare? E poi ancora: l'erotismo può integrarsi all'amore o lo esclude necessariamente? La spinta appropriativa e i fantasmi della gelosia caratterizzano ogni amore o sono solo i sintomi di una malattia inestirpabile? Cosa accade quando uno dei due tradisce la promessa? Cosa è un tradimento e quali sono le ferite che apre? È possibile il perdono nella vita amorosa? E la violenza? È una parte ineliminabile dell'amore o la sua profanazione più estrema? Cosa accade quando un amore finisce, quando dell'estasi del primo incontro e della luce del 'per sempre' non resta che cenere? È possibile sopravvivere alla morte di un amore che voleva essere per sempre? E qual è il mistero che accompagna gli amori che sanno durare senza rassegnarsi alla morte del desiderio, quegli amori che conoscono la meraviglia di una 'quiete accesa', come la definiva poeticamente Ungaretti? In sette brevi lezioni Massimo Recalcati scandaglia tutti questi interrogativi e offre ai suoi lettori i testi del programma televisivo 'Lessico amoroso'.", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-2-7", 128, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Nuotare, fluttuare, volare", "Daniel Glattauer", "6788807035708", null, null, "Due famiglie borghesi si regalano una vacanza in Toscana. Sono i Binder e gli Strobl-Marinek; quattro adulti, quattro figli. Li aspettano giornate oziose, bagni in piscina e aperitivi al tramonto. I Binder hanno una grande tenuta dove producono vino, mentre gli Strobl-Marinek sono un accademico e una politica ambientalista in ascesa. Quando la loro figlia quattordicenne, perennemente trincerata dietro il cellulare, chiede di poter invitare una compagna di scuola, subito acconsentono. Aayana è una giovane profuga somala, sarà l’occasione per farla rilassare e svagare. Neanche il tempo di arrivare che la vacanza si trasforma in tragedia. Quanto vale una vita umana? Ogni vita è uguale? Tra sensi di colpa, un acceso dibattito legale e mediatico sulle responsabilità mancate e forse la nascita di una tenera storia d’amore, Daniel Glattauer costruisce un romanzo intenso e graffiante, che mette in luce tutte le sue abilità: lo sguardo lucido del giornalista; i dialoghi brillanti; l’ironia e la tenerezza di “Le ho mai raccontato del vento del Nord”. E denuncia i vizi, i limiti e l’ipocrisia di una certa società privilegiata, per dare finalmente voce a chi di solito non ne ha.", 0, 3, '["page_1", "page_2", "page_3", "page_4"]', false, "2021-5-9", 288, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Germanico", "Valerio Massimo Manfredi", "1788804737438", null, null, "Mai era accaduto prima nella storia di Roma che due giovani dell'aristocrazia si amassero in modo così incondizionato. Dal momento in cui, giovanissimi, si riconosceranno come spiriti affini, Germanico e Agrippina non si separeranno più. Il vincolo che li unisce, del resto, è il coronamento di una grande passione, non certo un impegno formale determinato da convenienze politiche. Quando il giovane comandante è chiamato a guidare le otto legioni stanziate lungo il fiume Reno per riscattare il nome dell'Impero dopo la disfatta di Teutoburgo, Agrippina decide di seguirlo in Germania. Nonostante sia incinta, partecipa da protagonista alla vita dell'accampamento, rivelando presto un ascendente sui soldati superiore persino a quello del marito. Fieri, impavidi, volitivi, entrambi sembrano dei predestinati: se Germanico, figlio del valoroso comandante Druso, è l'uomo più indicato a succedere al vecchio imperatore Augusto, di cui è il pupillo, Agrippina, figlia di Marco Vipsanio Agrippa, l'eroe di Azio, ma soprattutto nipote di Augusto, rappresenta l'esempio più fulgido della matrona romana. Eppure, alla morte di Augusto per loro le cose si mettono male. Nel testamento l'imperatore ha designato il figliastro Tiberio come suo successore. Livia, sua madre – avversaria di Agrippina –, che ha sempre agito perché il marito favorisse il figlio Tiberio, detiene adesso un potere illimitato. Amati dalla gente e dai soldati così come temuti dal potere, Germanico e Agrippina accetteranno con spavalda consapevolezza il loro destino. Anni dopo la loro morte, sarà il centurione Quinto Sergio Sabino – un leale servitore dello Stato che ha avuto la ventura di essere testimone delle loro gesta – a raccontare nelle sue memorie chi furono l'imperatore mancato e la sua sposa guerriera, e in che modo Tiberio e Livia si accanirono su di loro.", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2022-7-19", 192, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Ci vediamo in agosto", "Gabriel García Márquez", "9788804781868", null, null, "Si sentì maliziosa, allegra, capace di tutto, e imbellita dalla mescolanza sacra della musica con il gin. Pensava che l’uomo del tavolo di fronte non l’avesse vista, però lo sorprese a osservarla quando lo guardò per la seconda volta. Lui arrossì. Lei sostenne il suo sguardo mentre lui controllava l’orologio da tasca con la catenina. Ogni anno, il 16 agosto, Ana Magdalena Bach – quasi cinquant’anni di età e una trentina scarsa di soddisfacente vita matrimoniale – raggiunge l’isola dei Caraibi dove è sepolta sua madre. Il traghetto, il taxi, un mazzo di gladioli e l’hotel: questo rituale esercita su di lei un irresistibile invito a trasformarsi – una volta all’anno - in un’altra donna, a esplorare la propria sensualità e a sondare la paura che silenziosa cova nel suo cuore. Lo stile inconfondibile di Márquez risplende in Ci vediamo in agosto, romanzo musicalissimo di variazioni sul tema che è nello stesso tempo un inno alla libertà, un omaggio alla femminilità, una riflessione sul mistero dell’amore e dei rimpianti.", 0, 4, '["page_1", "page_2", "page_3", "page_4"]', false, "2023-10-18", 120, false);
insert into libri(titolo, autore, codice_ISBN, data_aggiunta, data_eliminazione, trama, numero_letture, rating, pagine, evidenza, data_pubblicazione, numero_pagine, mark) 
values("Five survive", "Holly Jackson", "5788817179782", null, null, "Sei ragazzi in camper viaggiano nella notte verso le agognate vacanze di primavera. A un tratto, una gomma a terra li costringe a fermarsi, ma quello che sembra un banale incidente di percorso, ben presto si trasforma in un incubo. Un puntino rosso si muove lungo la fiancata del camper. Un rumore sordo. Odore di benzina. Qualcuno ha sparato al serbatoio. Là fuori, nell’oscurità, è appostato un cecchino e loro non possono fuggire, né comunicare con l’esterno perché i cellulari non funzionano: il loro aggressore ha messo fuori uso le celle telefoniche e comunica attraverso un walkie talkie appeso allo specchietto del camper. Ma la scoperta più agghiacciante è capire che non sono vittime casuali: il killer li conosce ed è venuto a cercare proprio uno di loro… In quelle otto ore che li separano dall’alba, le più lunghe della loro vita, molti segreti verranno svelati e la tensione tra i sei amici raggiungerà livelli fatali. Alla fine di quella lunga notte saranno ancora tutti insieme?", 0, 5, '["page_1", "page_2", "page_3", "page_4"]', false, "2024-6-28", 444, false);

insert into utenti(nome, cognome, email) values("Gabriele", "Zhou", "dreamwalker579@gmail.com");
insert into utenti(nome, cognome, email) values("Mario", "Rossi", "hello@gmail.com");

insert into utenti_libri(lista_libri, lista_libri_eliminati) values("[]", "[]");